--------------------------------------------------------
--  File created - «·À·«À«¡-‰Ê›„»—-02-2021   
--------------------------------------------------------
DROP TABLE "SYSTEM"."BUS";
DROP TABLE "SYSTEM"."CLIENTS";
DROP TABLE "SYSTEM"."EMPLOYES";
DROP TABLE "SYSTEM"."EQUIPEMENTS";
DROP TABLE "SYSTEM"."GERER";
DROP TABLE "SYSTEM"."REPARATION";
DROP TABLE "SYSTEM"."REPARER";
DROP TABLE "SYSTEM"."TICKETS";
DROP TABLE "SYSTEM"."TRAITER";
--------------------------------------------------------
--  DDL for Table BUS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BUS" 
   (	"MARQUE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"MATRICULE" NUMBER, 
	"PUISSANCE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENTS" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"ID_C" NUMBER, 
	"PDP" VARCHAR2(20 BYTE), 
	"NUMTEL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYES" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"ADRESSE" DATE, 
	"NUM_TEL" NUMBER, 
	"MAIL" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EQUIPEMENTS" 
   (	"CODE_A_BARRE" NUMBER, 
	"NBRE" NUMBER, 
	"DATE_ACHAT" DATE, 
	"PRIX" NUMBER, 
	"TYPEE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GERER" 
   (	"COLUMN1" NUMBER, 
	"COLUMN2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPARATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REPARATION" 
   (	"ETAT" BINARY_DOUBLE, 
	"PRIX" NUMBER, 
	"DATE_REPARATION" DATE, 
	"REFFERENCE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPARER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REPARER" 
   (	"COLUMN1" NUMBER, 
	"COLUMN2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKETS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TICKETS" 
   (	"TYPE" NUMBER, 
	"PNT_DPR" VARCHAR2(20 BYTE), 
	"PNT_ARV" VARCHAR2(20 BYTE), 
	"CODE" NUMBER, 
	"T_DATE" DATE, 
	"PRIXX" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRAITER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TRAITER" 
   (	"COLUMN1" NUMBER, 
	"COLUMN2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.BUS
SET DEFINE OFF;
Insert into SYSTEM.BUS (MARQUE,TYPE,MATRICULE,PUISSANCE) values ('oijoioijjo','ijoijoi',575,57527);
Insert into SYSTEM.BUS (MARQUE,TYPE,MATRICULE,PUISSANCE) values ('hgjbh','hjjh',8697,7896896);
Insert into SYSTEM.BUS (MARQUE,TYPE,MATRICULE,PUISSANCE) values ('toyota','x200',212,121);
Insert into SYSTEM.BUS (MARQUE,TYPE,MATRICULE,PUISSANCE) values ('kjnoj','jnkjn',385454,4654);
Insert into SYSTEM.BUS (MARQUE,TYPE,MATRICULE,PUISSANCE) values ('fghgf','dfgdf',87587,5785);
Insert into SYSTEM.BUS (MARQUE,TYPE,MATRICULE,PUISSANCE) values ('mmazkgdzr','gdge',53256,200);
Insert into SYSTEM.BUS (MARQUE,TYPE,MATRICULE,PUISSANCE) values ('jh,vj','khkh',6855675,5757);
Insert into SYSTEM.BUS (MARQUE,TYPE,MATRICULE,PUISSANCE) values ('9155','9155',9155,9155);
REM INSERTING into SYSTEM.CLIENTS
SET DEFINE OFF;
REM INSERTING into SYSTEM.EMPLOYES
SET DEFINE OFF;
REM INSERTING into SYSTEM.EQUIPEMENTS
SET DEFINE OFF;
REM INSERTING into SYSTEM.GERER
SET DEFINE OFF;
REM INSERTING into SYSTEM.REPARATION
SET DEFINE OFF;
REM INSERTING into SYSTEM.REPARER
SET DEFINE OFF;
REM INSERTING into SYSTEM.TICKETS
SET DEFINE OFF;
REM INSERTING into SYSTEM.TRAITER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."BUS_PK" ON "SYSTEM"."BUS" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CLIENTS_PK" ON "SYSTEM"."CLIENTS" ("ID_C") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYES_PK" ON "SYSTEM"."EMPLOYES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EQUIPEMENTS_PK" ON "SYSTEM"."EQUIPEMENTS" ("CODE_A_BARRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPARATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."REPARATION_PK" ON "SYSTEM"."REPARATION" ("REFFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKETS_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TICKETS_PK1" ON "SYSTEM"."TICKETS" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BUS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BUS" ADD CONSTRAINT "BUS_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."BUS" MODIFY ("PUISSANCE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BUS" MODIFY ("MATRICULE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BUS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BUS" MODIFY ("MARQUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("ID_C")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CLIENTS" MODIFY ("ID_C" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_PK" PRIMARY KEY ("CODE_A_BARRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."EQUIPEMENTS" MODIFY ("CODE_A_BARRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPARATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REPARATION" ADD CONSTRAINT "REPARATION_PK" PRIMARY KEY ("REFFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."REPARATION" MODIFY ("REFFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKETS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TICKETS" ADD CONSTRAINT "TICKETS_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TICKETS" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYES" ADD CONSTRAINT "MATRICULE" FOREIGN KEY ("ID")
	  REFERENCES "SYSTEM"."BUS" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GERER" ADD CONSTRAINT "CODEE" FOREIGN KEY ("COLUMN2")
	  REFERENCES "SYSTEM"."TICKETS" ("CODE") ENABLE;
  ALTER TABLE "SYSTEM"."GERER" ADD CONSTRAINT "ID_C" FOREIGN KEY ("COLUMN1")
	  REFERENCES "SYSTEM"."CLIENTS" ("ID_C") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPARER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REPARER" ADD CONSTRAINT "IDEE" FOREIGN KEY ("COLUMN2")
	  REFERENCES "SYSTEM"."EMPLOYES" ("ID") ENABLE;
  ALTER TABLE "SYSTEM"."REPARER" ADD CONSTRAINT "MATRICULEE" FOREIGN KEY ("COLUMN1")
	  REFERENCES "SYSTEM"."BUS" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKETS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TICKETS" ADD CONSTRAINT "IDC" FOREIGN KEY ("CODE")
	  REFERENCES "SYSTEM"."CLIENTS" ("ID_C") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRAITER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TRAITER" ADD CONSTRAINT "ID" FOREIGN KEY ("COLUMN1")
	  REFERENCES "SYSTEM"."EMPLOYES" ("ID") ENABLE;
